image: harbor-repo.vmware.com/cloudlens/docker

variables:
  # When using dind service we need to instruct docker, to talk with the
  # daemon started inside of the service. The daemon is available with
  # a network connection instead of the default /var/run/docker.sock socket.
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
  #
  # If you're using GitLab Runner 12.7 or earlier with the Kubernetes executor and Kubernetes 1.6 or earlier,
  # the variable must be set to tcp://localhost:2375 because of how the
  # Kubernetes executor connects services to the job container
  # DOCKER_HOST: tcp://localhost:2375
  #
  DOCKER_HOST: tcp://localhost:2375
  #
  # This will instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""

services:
- harbor-repo.vmware.com/cloudlens/docker:dind

before_script:
- docker run -d --rm -it --name nats -p 4222:4222 -p 8222:8222 harbor-repo.vmware.com/dsosedov_samples/nats-streaming:alpine

build:
  stage: build
  script: docker build --build-arg DOCKER_REPO=$DOCKER_REPO .
