// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.dsosedov.natsproducer.messages;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.dsosedov.natsproducer.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string text = 1;</code>
   * @return Whether the text field is set.
   */
  boolean hasText();
  /**
   * <code>optional string text = 1;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>optional string text = 1;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
