// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.dsosedov.natsproducer.messages;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dsosedov_natsproducer_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dsosedov_natsproducer_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rMessage.proto\022\031com.dsosedov.natsproduc" +
      "er\"%\n\007Message\022\021\n\004text\030\001 \001(\tH\000\210\001\001B\007\n\005_tex" +
      "tB4\n\"com.dsosedov.natsproducer.messagesB" +
      "\014MessageProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_dsosedov_natsproducer_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_dsosedov_natsproducer_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dsosedov_natsproducer_Message_descriptor,
        new java.lang.String[] { "Text", "Text", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
